### ISSUE TITLE
Cannot read property 'isUser' of undefined

### ISSUE THREAD

**Issue by cosmicespresso** [Kallirroi/bot_test#50]
![image](https://user-images.githubusercontent.com/10440556/79020810-da162400-7b47-11ea-8327-51ec860afd87.png)
I see this often when I breeze through the steps super fast, first time I see it when I take a while to chat

**Comment by agnescameron** [comment]
ooh interesting: this feels like something where the bot response hasn't loaded before it's trying to get appended... I'll look into it

**Comment by agnescameron** [comment]
related bug: `groups[endIndex] is undefined`

![Screen Shot 2020-04-13 at 15 42 12](https://user-images.githubusercontent.com/16444898/79154443-8866d700-7d9d-11ea-888b-b64f14519c16.png)

**Comment by agnescameron** [comment]
(this is on firefox, moderately fast navigation, between user challenge and bot challenge rounds)

**Comment by cosmicespresso** [comment]
~I will spend some time trying to replicate this~

I can't seem to replicate this - I did add a check for an undefined `groups` though, in case that helps.

**Comment by agnescameron** [comment]
<img width="473" alt="Screen Shot 2020-04-15 at 20 35 18" src="https://user-images.githubusercontent.com/16444898/79402047-cbb97500-7f58-11ea-93cc-11c62c91eac5.png">
still happening: I have a feeling that having the check in the same if statement doesn't actually fix that kind of bug though. once i'm finished on this branch I'll take a look at it

**Comment by cosmicespresso** [comment]
true maybe nesting the conditionals would be a better way to check, but its still a dumb way to go about it...

**Comment by cosmicespresso** [comment]
lets start keeping track of when in the flow this error appears

**Comment by cosmicespresso** [comment]
![image](https://user-images.githubusercontent.com/10440556/79402508-125b9f00-7f5a-11ea-8bf2-6243a58feada.png)
ah just got it as well!! Last round.

**Comment by agnescameron** [comment]
> true maybe nesting the conditionals would be a better way to check, but its still a dumb way to go about it...

yeah i hate it... there must be a better way

**Comment by agnescameron** [comment]
and i got it there too. 🤔

**Comment by cosmicespresso** [comment]
Not sure if thats it, but there was a glitch with props which I fixed here https://github.com/Kallirroi/bot_or_not/commit/db96ae6ac1b1511a0a76d942b430036cdf9c2d88, haven't gotten it in a few tries...but also not convinced that's the real issue.

**Comment by agnescameron** [comment]
<img width="557" alt="Screen Shot 2020-04-21 at 10 41 53" src="https://user-images.githubusercontent.com/16444898/79879529-ccb92f00-83bc-11ea-83bd-7687c018fe48.png">
nested conditionals stops it from breaking, gonna try and see why it's happening also

**Comment by agnescameron** [comment]
NB: i got this 100% of the time when i try and process the response normally (instead of just appending it) at the start of the truth round (people said the bot was too fast in the feedback)... so there's a clue

**Comment by agnescameron** [comment]
```
		if (this.props && this.props.isBotTyping) {
			const endIndex = groups.length - 1;
			if(groups[endIndex]){
				if (groups[endIndex].isUser) {
					groups.push({isUser: false, messages: [null]});
				} else {
					groups[endIndex].messages.push(null);
				}
			}
		}
```


OK: I think this is actually the fix we want. What's happening is:

-- `groups` gets cleared between rounds (which solves the earlier bug where there would be new messages)
-- there's nothing in `groups`, so `groups.length-1` is -1, which isn't an index for groups.
-- even if we check so it can't be below 0, there's nothing there and you still get an error
-- we don't want to not empty groups

gonna close this for now we can always replace with a more elegant solution if we find one, but this works fine

**Comment by agnescameron** [comment]
...that said, i'm still not 100% on what this function is meant to do... so perhaps it's also possible just to get rid entirely
